expose_php=Off
display_errors=Off
display_startup_errors=Off
log_errors=On
zend.exception_ignore_args=On
error_log=/dev/stderr
memory_limit=192M
upload_max_filesize=64K
post_max_size=128K
file_uploads=Off
opcache.enable=1
opcache.validate_timestamps=0
