<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('This migration requires PostgreSQL.');
        }

        DB::unprepared(<<<'SQL'
            CREATE TABLE users (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                display_name varchar(50) NOT NULL,
                email varchar(254) NOT NULL,
                password varchar(255) NOT NULL,
                role varchar(16) NOT NULL,
                is_active boolean NOT NULL DEFAULT false,
                auth_version integer NOT NULL DEFAULT 1,
                created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT users_id_positive CHECK (id > 0),
                CONSTRAINT users_display_name_length CHECK (char_length(display_name) BETWEEN 1 AND 50),
                CONSTRAINT users_email_length CHECK (char_length(email) BETWEEN 1 AND 254),
                CONSTRAINT users_email_normalized CHECK (email = lower(btrim(email))),
                CONSTRAINT users_email_ascii CHECK (email ~ '^[!-~]+$'),
                CONSTRAINT users_role_allowed CHECK (role IN ('employee', 'it_staff')),
                CONSTRAINT users_auth_version_positive CHECK (auth_version > 0),
                CONSTRAINT users_email_unique UNIQUE (email),
                CONSTRAINT users_id_role_unique UNIQUE (id, role)
            )
            SQL);
        DB::statement("CREATE INDEX users_active_it_id ON users (id) WHERE role = 'it_staff' AND is_active = true");
    }

    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
