<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE service_requests (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
                requester_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
                title varchar(100) NOT NULL CHECK (char_length(title) BETWEEN 1 AND 100 AND position(chr(10) in title) = 0 AND position(chr(13) in title) = 0),
                body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 5000),
                category varchar(16) NOT NULL CHECK (category IN ('inquiry', 'bug', 'improvement')),
                assignee_id bigint,
                assignee_role varchar(16) NOT NULL DEFAULT 'it_staff' CHECK (assignee_role = 'it_staff'),
                status varchar(24) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'waiting_confirmation', 'completed')),
                version integer NOT NULL DEFAULT 1 CHECK (version > 0),
                created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT service_requests_assignee_required CHECK (status = 'open' OR assignee_id IS NOT NULL),
                CONSTRAINT service_requests_assignee_it FOREIGN KEY (assignee_id, assignee_role)
                    REFERENCES users(id, role) MATCH SIMPLE ON DELETE RESTRICT ON UPDATE RESTRICT
            );
            CREATE INDEX service_requests_created_id ON service_requests (created_at DESC, id DESC);
            CREATE INDEX service_requests_requester_created_id ON service_requests (requester_id, created_at DESC, id DESC);
            CREATE INDEX service_requests_assignee ON service_requests (assignee_id, assignee_role);
            SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE service_requests');
    }
};
