<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE comments (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
                service_request_id bigint NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE ON UPDATE RESTRICT,
                author_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
                body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
                created_at timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX comments_request_created_id ON comments (service_request_id, created_at ASC, id ASC);
            CREATE INDEX comments_author ON comments (author_id);
            SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE comments');
    }
};
