"""Pinned Gitleaks setup and scans. Python standard library only."""

import argparse
import hashlib
import io
import json
import os
from pathlib import Path
import platform
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
import zipfile


ROOT = Path(__file__).resolve().parents[1]
CONFIG = json.loads((ROOT / "config/gitleaks.json").read_text(encoding="utf-8"))


def git(*args):
    return subprocess.run(
        ["git", *args], cwd=ROOT, check=True, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    ).stdout


def binary_path():
    machine = platform.machine().lower()
    if machine not in ("amd64", "x86_64"):
        raise RuntimeError("Only Windows/Linux x64 archives are configured.")
    target = platform.system().lower() + "_x64"
    if target not in CONFIG["archives"]:
        raise RuntimeError("Only Windows/Linux x64 archives are configured.")
    name = "gitleaks.exe" if os.name == "nt" else "gitleaks"
    return ROOT / ".tools/gitleaks" / CONFIG["version"] / target / name, target


def verify_binary():
    binary, _ = binary_path()
    if not binary.is_file():
        raise RuntimeError("Gitleaks is missing. Run: python scripts/secrets.py install")
    result = subprocess.run(
        [str(binary), "version"], check=True, capture_output=True, text=True,
    )
    if result.stdout.strip().removeprefix("v") != CONFIG["version"]:
        raise RuntimeError("Gitleaks version mismatch; reinstall the pinned release.")
    return binary


def install():
    binary, target = binary_path()
    archive = CONFIG["archives"][target]
    url = (
        "https://github.com/gitleaks/gitleaks/releases/download/v"
        + CONFIG["version"] + "/" + archive["name"]
    )
    with urllib.request.urlopen(url, timeout=60) as response:
        data = response.read()
    if hashlib.sha256(data).hexdigest() != archive["sha256"]:
        raise RuntimeError("Downloaded archive SHA-256 does not match the pinned value.")
    # Extract only the expected executable, never arbitrary archive paths.
    if archive["name"].endswith(".zip"):
        with zipfile.ZipFile(io.BytesIO(data)) as package:
            executable = package.read(binary.name)
    else:
        with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as package:
            with package.extractfile(binary.name) as source:
                executable = source.read()
    binary.parent.mkdir(parents=True, exist_ok=True)
    temporary = binary.with_suffix(".download")
    temporary.write_bytes(executable)
    temporary.chmod(0o755)
    temporary.replace(binary)
    verify_binary()
    print(f"Installed Gitleaks {CONFIG['version']} ({target}); archive SHA-256 verified.")


def install_hook():
    verify_binary()
    configured = subprocess.run(
        ["git", "config", "--get", "core.hooksPath"], cwd=ROOT, capture_output=True,
    )
    if configured.returncode != 1:
        raise RuntimeError("core.hooksPath is set or unreadable; see docs/development.md for coexistence.")
    hook = Path(os.fsdecode(git("rev-parse", "--git-path", "hooks/pre-commit")).strip())
    if not hook.is_absolute():
        hook = ROOT / hook
    # Git for Windows runs hooks with its bundled sh; Python need not be on VS Code's PATH.
    content = (
        "#!/bin/sh\n# Portfolio Gitleaks hook; generated by scripts/secrets.py.\n"
        + "exec " + shlex.quote(Path(sys.executable).as_posix())
        + " -I scripts/secrets.py staged\n"
    )
    if hook.is_symlink() or (hook.exists() and hook.read_bytes() != content.encode("utf-8")):
        raise RuntimeError("An existing pre-commit hook was preserved; see docs/development.md.")
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(content, encoding="utf-8", newline="\n")
    hook.chmod(0o755)
    print("Installed local pre-commit hook (existing hooks are never overwritten).")


def scan(mode):
    binary = verify_binary()
    common = [
        "--config", str(ROOT / ".gitleaks.toml"), "--redact=100",
        "--no-banner", "--no-color", "--verbose", "--exit-code=1",
        "--ignore-gitleaks-allow",
    ]
    if mode == "files":
        # Include tracked files even if newly ignored, plus untracked nonignored files.
        # Scan a snapshot to avoid .git, downloaded tools, and real ignored local values.
        names = git("ls-files", "--cached", "--others", "--exclude-standard", "-z")
        with tempfile.TemporaryDirectory(prefix="portfolio-gitleaks-files-") as folder:
            for raw in set(names.split(b"\0")) - {b""}:
                relative = Path(os.fsdecode(raw))
                source = ROOT / relative
                if source.is_symlink():
                    raise RuntimeError("A symbolic link requires explicit review before file scanning.")
                if not source.exists():
                    continue  # A tracked file deleted from the working tree.
                if not source.is_file() or not source.resolve().is_relative_to(ROOT):
                    raise RuntimeError("Unsupported file or path outside the repository.")
                destination = Path(folder) / relative
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, destination)
            return subprocess.run([str(binary), "dir", *common, folder], cwd=ROOT).returncode
    options = ["--pre-commit", "--staged"] if mode == "staged" else ["--log-opts=--all --full-history"]
    if mode == "history":
        # No history is an error for this mode, not a successful empty scan.
        git("rev-parse", "--verify", "HEAD")
    return subprocess.run([str(binary), "git", *common, *options, "."], cwd=ROOT).returncode


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("install", "install-hook", "staged", "files", "history"))
    args = parser.parse_args()
    try:
        actual_root = Path(os.fsdecode(git("rev-parse", "--show-toplevel")).strip()).resolve()
        if actual_root != ROOT:
            raise RuntimeError("Run this tool from its own Git repository.")
        if args.command == "install":
            install()
        elif args.command == "install-hook":
            install_hook()
        else:
            return scan(args.command)
    except subprocess.CalledProcessError:
        print("ERROR: Git or Gitleaks failed. Scan/setup did not pass.", file=sys.stderr)
        return 2
    except (OSError, RuntimeError, ValueError, KeyError, tarfile.TarError, zipfile.BadZipFile) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
